### ISSUE TITLE
Prepare for user demo 2

### ISSUE THREAD

**Issue by cristiklein** [arvos-dev/arvos#24]
User demo 1 was a great success! We learned a lot. Before heading for user demo 2, we want to prepare the following:

- [ ] Package ARVOS in a GitHub Action
  - [ ] Make sure ARVOS fails the pipeline if vulnerabilities are found
  - [ ] ARVOS should "feel" like `mvn test`, i.e., no separate workload generator needs to be execute
- [ ] Make the whole output a lot more readable and intuitive
  - [ ] Remove "spread" from output
  - [ ] Make stack trace look more "data-ish"
  - [ ] Group output by CVE, e.g., "This vulnerability is affecting 3 other code paths. Run ARVOS with --show-all to show all code paths."

Next user test would look as follows:

1. We give write access to the user to a GitHub repo.
2. We ask the user to clone the repo on their laptop.
3. We ask the user to make a trivial change, e.g., "change hello world to hello ARVOS".
4. We ask the user to inspect the output of the failed CI/CD pipeline.
5. We ask the user:
   - What do they think has happened?
   - What would they do now?

**Comment by ayoubeddafali** [comment]
>     * [x]  Package ARVOS in a GitHub Action => Github action created for the following sample project https://github.com/ayoubeddafali/spring-vulnerable-app/actions
>       
>       * [x]  Make sure ARVOS fails the pipeline if vulnerabilities are found => Pipeline fails if vulnerabilities found
>       * [ ]  ARVOS should "feel" like `mvn test`, i.e., no separate workload generator needs to be execute
> 
>     * [x]  Make the whole output a lot more readable and intuitive => Highlighting & Relevant stacktraces has been aded
>       
>       * [x]  Remove "spread" from output => spread field has been removed, and repository field has been made more clearer by prepending `https://github.com/` 
>       * [x]  Make stack trace look more "data-ish" => Stack trace is more user friendly now  
![image](https://user-images.githubusercontent.com/11875804/170058854-79569e4c-1bf1-46ce-b517-e58afc120bd8.png)

>       * [ ]  Group output by CVE, e.g., "This vulnerability is affecting 3 other code paths. Run ARVOS with --show-all to show all code paths."

**Comment by cristiklein** [comment]
I love the screenshot!

@ayoubeddafali Feel free to create issues for each checkbox item (see [issue task list](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists#about-issue-task-lists)). Nothing beats the adrenaline rush when closing an issue with a PR. 🤣

**Comment by ayoubeddafali** [comment]
- [x] https://github.com/arvos-dev/arvos/issues/25
  - [x] https://github.com/arvos-dev/arvos/issues/26
  - https://github.com/arvos-dev/arvos/issues/27

- [x] Intuitive & readable output : #23 
  - [x] https://github.com/arvos-dev/arvos/issues/28
  - [x] https://github.com/arvos-dev/arvos/issues/29
  - [ ] https://github.com/arvos-dev/arvos/issues/30
